### ISSUE TITLE
[FEATURE] Install Helm from GitHub

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-actions/openshift-tools-installer#49]
### Is your feature request related to a problem? Please describe.

The helm version being installed is not the latest: https://github.com/helm/helm/releases
it installs 3.6.2

### Describe the solution you'd like

Stay current on releases.

### Describe alternatives you've considered

azure/setup-helm

**Comment by tetchel** [comment]
We don't control which versions are available on the OpenShift mirror. 3.6.2 is the latest version there https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/helm/

However I can reword this issue to allow installing helm from github to get the latest.

IIRC we did not do this right away because helm's releases are structured in a complex way.

**Comment by davidkarlsen** [comment]
> IIRC we did not do this right away because helm's releases are structured in a complex way.

What's complex about it? Is there something we can improve?

**Comment by Divyansh42** [comment]
The complexity that we faced is due to the unavailability of `helm` binaries in the download asset of the GitHub release, it's only having checksums.
While other tools that we support have all the binaries available in the download asset. e.g. https://github.com/knative/client/releases/tag/v0.25.0

It would be great if helm also has binaries available with the GitHub releases.

**Comment by tetchel** [comment]
Sorry, I didn't read Divyanshu's comment properly previously. 

This is similar to #48, we simply can't do it because the binaries are not on GitHub.
